Repository the132Debuggers/cse110-sp23-the132Debuggers, pull requests merged in 2023-04, with the labels that each got.

#9 ci(lint): added eslint as prettier for code style
  .eslintrc.yml
  .github/workflows/commitlint.yaml
  .github/workflows/common.yaml
  .gitignore
  .prettierignore
  .prettierrc.json
  commitlint.config.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#10 docs(readme): added development guide
  README.md
Labels: documentation

#18 build(*): admin/team.md and additional branding images
  admin/branding/logo.png
  admin/branding/team-photo.jpg
  admin/team.md
Labels: mangement
